# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Use Ubuntu box
  config.vm.box = "hashicorp/bionic64"

  # Use sh to initialice vm
  config.vm.provision :shell, path: "bootstrap.sh"

  # This line is important to expose the server in the port 3000
  config.vm.network "forwarded_port", guest: 3000, host: 3000
end
